[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hydraflow"
version = "0.2.14"
description = "Hydraflow integrates Hydra and MLflow to manage and track machine learning experiments."
readme = "README.md"
license = "MIT"
authors = [{ name = "daizutabi", email = "daizutabi@gmail.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
dependencies = [
  "hydra-core>1.3",
  "joblib",
  "mlflow>2.15",
  "rich",
  "setuptools",
  "watchdog",
  "watchfiles",
]

[project.optional-dependencies]
dev = [
  "pytest-asyncio",
  "pytest-clarity",
  "pytest-cov",
  "pytest-randomly",
  "pytest-xdist",
]

[project.urls]
Documentation = "https://github.com/daizutabi/hydraflow"
Source = "https://github.com/daizutabi/hydraflow"
Issues = "https://github.com/daizutabi/hydraflow/issues"

[tool.hatch.build.targets.sdist]
exclude = ["/.github", "/docs"]

[tool.hatch.build.targets.wheel]
packages = ["src/hydraflow"]

[tool.pytest.ini_options]
addopts = [
  "--doctest-modules",
  "--cov=hydraflow",
  "--cov-report=lcov:lcov.info",
]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]
filterwarnings = ['ignore:pkg_resources is deprecated:DeprecationWarning']
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.report]
exclude_lines = ["no cov", "raise NotImplementedError", "if TYPE_CHECKING:"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
unfixable = ["F401", "RUF100"]
