[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "whoau"
version = "0.1.1"
description = "Have any questions? Take a moment to find out!"
license = "MIT"
authors = [ "dotpie <mail@dotpie.dev>",]
maintainers = [ "dotpie <mail@dotpie.dev>",]
readme = "README.md"
homepage = "https://github.com/dotpie/dotpie"
repository = "https://github.com/dotpie/whoau"
keywords = ["hello world", "python", "profile", "readme",]


[tool.poetry.dependencies]
python = "^3.8"
rich = "^13.7.1"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"

[tool.poetry.scripts]
dotpie = "whoau.main:main"
# dotpie = "dotpie.main:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/dotpie/whoau/issues"


# # For GitHub Actions PyTest
# [tool.pytest.ini_options]
# rootdir = "src"
