[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_http"
version = "0.3.6"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (HTTP modules)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "Flask>=3.0.3",
    "pip>=24.2",
    "pypomes_core>=1.4.9",
    "pypomes_jwt>=0.3.8",
    "requests>=2.32.3",
    "setuptools>=74.1.2",
    "wheel>=0.44.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-HTTP"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-HTTP/issues"
