[project]
name = "langchain-pangu"
version = "0.2.3"
authors = [
    { name = "MeiK", email = "meik2333@gmail.com" },
]
description = "langchain-pangu"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "langchain==0.2.15",
    "langchain-community==0.2.15",
    "langgraph==0.2.16",
    "langchain_openai==0.1.23",
    "jinja2==3.1.4",
    "httpx==0.27.2",
    "h2==4.1.0"
]

[project.urls]
Homepage = "https://github.com/MeiK2333/langchain-pangu"
Issues = "https://github.com/MeiK2333/langchain-pangu/issues"

[tool.setuptools.package-data]
"*" = ["*.pt", "*.jinja2"]
