# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel","Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "distancia"
version = "0.0.43"
description = "distance metrics"
readme = "README.md"
authors = [{ name = "Yves Mercadier", email = "info@realpython.com" }]
license = { file = "LICENSE.txt" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["distance", "metrics", "space"]
dependencies = []
requires-python = ">=3.0"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://pypi.org/project/distancia/"

[project.scripts]
