[tool.poetry]
name = "base-parser"
version = "0.1.22"
description = ""
authors = ["Константин Зубченко <k.zubchenko@bi.zone>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
