[tool.poetry]
name = "krakenpull"
version = "1.0.0"
description = "A user friendly Kraken API client using pydantic ğŸ™"
authors = ["marc <marc@mawaie.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.7.0"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
ruff = "^0.4.1"
black = "^24.4.0"
mypy = "^1.9.0"
types-requests = "^2.31.0.20240406"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
