[tool.poetry]
name = "tma-authenticator"
version = "1.1.0"
description = "Verifying telegram user token."
authors = ["Ivan Kochelorov <imkochelorov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0"
fastapi = "^0.112.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
