[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0.0",
]

[project]
authors = [
    { email = "johannes-programming@mailfence.com", name = "Johannes" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []
description = "framing"
keywords = []
name = "framing"
readme = "README.rst"
requires-python = ">=3.12.4"
version = "0.0.1"

[project.license]
file = "LICENSE.txt"

[project.urls]
Documentation = "https://pypi.org/project/framing"
Download = "https://pypi.org/project/framing/#files"
Source = "https://github.com/johannes-programming/framing"
