[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "memorial"
version = "0.0.6"
authors = [
  { name="Jet", email="taijunjet@hotmail.com" },
]
description = "Replay Buffer Implementations for RL"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy", "prefetch-generator"]
keywords = ["Machine Learning", "Reinforcement Learning"]
license = { file="./LICENSE.txt" }

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-xdist",
  "pre-commit",
  "torch",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["memorial", "memorial.*"]

[project.urls]
"Homepage" = "https://github.com/jjshoots/Memorial"

#######################################################################################
# linters
#######################################################################################
[tool.pyright]
reportMissingImports = "none"
include = ["memorial", "test"]
