[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["templates"]

[project]
name = "let-me-scroll-it"
version = "0.0.2"
requires-python = ">=3.9"
dependencies = [
    "jinja2",
    "unyt",
    "pydantic"
]
authors = [
  { name="Josh Borrow", email="josh@joshborrow.com" },
]
readme = "README.md"
description = "A command-line utility for placing figures in a static webpage"


[project.scripts]
lmsi = "lmsi.cli:main"

[tool.ruff.lint]
extend-select = ["I"]