[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "ras-commander"
dynamic = ["version"]
description = "A library for automating HEC-RAS operations using python functions."
authors = [{name = "William Katzenmeyer, P.E., C.F.M.", email = "heccommander@gmail.com"}]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/billk-FM/ras-commander"

[tool.setuptools_scm]
version_scheme = "release-branch-semver"  # This ensures clean, stable version numbers
local_scheme = "no-local-version"  # Avoid any local identifiers like +g684fd17
write_to = "ras_commander/_version.py"

[tool.setuptools]
packages = ["ras_commander"]
