[project]
name = "beancount-importer-rules"
version = "0.1.7.dev8"
description = "Beancount importer rules engine"
authors = [
    { name = "Zeno Jiricek", email = "airtonix@users.noreply.github.com" },
]
dependencies = [
    "beancount-parser>=1.2.3",
    "beancount-black>=1.0.4",
    "jinja2>=3.1.4",
    "pyyaml>=6.0.2",
    "pydantic>=2.8.2",
    "pytz>=2024.1",
    "click>=8.1.7",
    "rich>=13.8.0",
    "types-PyYAML>=6.0.12.20240808",
    "types-Pygments>=2.18.0.20240506",
    "types-regex>=2024.7.24.20240726",
    "arrow>=1.3.0",
    "pyarrow>=17.0.0",
    "ipykernel>=6.29.5",
]
requires-python = ">=3.12"
readme = "README.md"

[project.license]
text = "MIT"

[project.scripts]
beancount-import = "beancount_importer_rules.cli:cli"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.3.2",
    "pytest-mock>=3.14.0",
    "rich>=13.8.0",
    "beancount==2.3.6",
    "pylance>=0.16.1",
    "ruff>=0.6.2",
    "pytest-md-report>=0.6.2",
    "mypy>=1.11.2",
    "pyright>=1.1.378",
    "pre-commit>=3.8.0",
    "mkdocs-material[imaging]>=9.5.34",
    "mkdocs>=1.6.1",
    "mkdocstrings>=0.26.0",
    "mkdocstrings-python",
    "mkdocs-autorefs>=1.2.0",
    "mike>=2.1.3",
    "pdm-bump>=0.9.8",
    "pdm-version>=2.1.0",
    "markdown>=3.7",
    "pymdown-extensions>=10.9",
    "pygments>=2.18.0",
    "pillow>=10.4.0",
    "cairosvg>=2.7.1",
    "xmltojson>=2.0.2",
    "detect-secrets>=1.5.0",
    "mkdocs-macros-plugin>=1.2.0",
]

[tool.pdm.build]
includes = [
    "beancount_importer_rules",
    "README.md",
    "pyproject.toml",
    "LICENSE",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
