[project]
name = "mysql-compare"
version = "0.6.9"
requires-python = ">=3.10"
dependencies = ["mysql-connector-python==9.0.0"]

[tool.setuptools]
packages = ["mysql_compare"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
