[project]
name = "frstool"
version = "1.0.3"
authors = [
  { name="Anton Shishkin", email="ashishkin@5sigma.co" },
]
dependencies = [
    'requests >= 2.32.3'
]
description = "Financial Resilience Score Tool Solution"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://financialresiliencescore.com"
Issues = "https://financialresiliencescore.com"