[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0.0",
]

[project]
authors = [
    { email = "johannes-programming@mailfence.com", name = "Johannes" },
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []
description = "Uniting some function utilities inside of one project."
keywords = []
name = "functricks"
readme = "README.rst"
requires-python = ">=3.10"
version = "1.0.1"

[project.license]
file = "LICENSE.txt"

[project.urls]
Documentation = "https://pypi.org/project/functricks"
Download = "https://pypi.org/project/functricks/#files"
Source = "https://github.com/johannes-programming/functricks"
