[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_jwt"
version = "0.3.5"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (JWT module)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "pip>=24.2",
    "PyJWT>=2.9.0",
    "pypomes_core>=1.4.9",
    "pypomes_crypto>=0.2.8",
    "setuptools>=74.1.2",
    "wheel>=0.44.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-JWT"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-JWT/issues"
