[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nordpool-daily-averages"
version= "1.1.42"
description = "REST api wrapper for nordpool average daily spot prices"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Topic :: Software Development :: Libraries"
]
authors = [{name = "Gunnar Svanberg", email = "gus.svanberg@gmail.com"}]
requires-python = ">=3.9"
dependencies = [
    "httpx",
    "pytz"
]

[project.urls]
Source = "https://github.com/g-svanberg/nordpool-imd-daily-average"
Documentation = "https://github.com/g-svanberg/nordpool-imd-daily-average/blob/main/README.md"
