[tool.poetry]
name = "samgis-lisa"
version = "1.0.2"
description = "SamGIS LISA"
authors = ["alessandro trinca tornidor <alessandro@trinca.tornidor.com>"]
license = "MIT"
readme = "README.md"

[metadata]
name = "samgis-lisa"
version = "1.0.2"


[tool.poetry.urls]
Source = "https://gitlab.com/aletrn/samgis_lisa"

[tool.poetry.dependencies]
gradio = "4.44.0"
python = ">=3.10,<3.11"
samgis-web = "1.0.14"
lisa-on-cuda = "1.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
