[tool.poetry]
name = "transcribe-cli"
version = "0.1.1"
description = ""
authors = ["Andrei Chenchik <andrei@chenchik.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
yt-dlp = "^2024.8.6"
assemblyai = "^0.33.0"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
transcribe = "transcribe-cli.cli:main"